import { Circuit, Driver, Constructor, RadioQuote, AeroHotspot, TriviaQuestion } from '../types';

export const CIRCUITS: Circuit[] = [
  {
    id: 'monaco',
    name: 'Circuit de Monaco',
    location: 'Monte Carlo',
    country: 'Monaco',
    flag: '🇲🇨',
    lengthKm: 3.337,
    laps: 78,
    corners: 19,
    drsZones: 1,
    lapRecord: { time: '1:12.909', driver: 'Lewis Hamilton', year: 2021 },
    svgPath: 'M 100 180 C 120 100, 160 80, 240 80 C 320 80, 360 120, 380 160 C 400 200, 380 260, 320 280 C 260 300, 220 280, 200 240 C 180 200, 160 220, 140 260 C 120 300, 80 260, 100 180 Z',
    sectors: [
      { id: 1, name: 'S1: Sainte Dévote & Beau Rivage', lengthKm: 1.05 },
      { id: 2, name: 'S2: Mirabeau, Hairpin & Tunnel', lengthKm: 1.22 },
      { id: 3, name: 'S3: Nouvelle Chicane & Rascasse', lengthKm: 1.067 },
    ],
    description: 'The ultimate test of precision and bravery through narrow city streets. Millimeters from barrier walls at 280 km/h with high aerodynamic downforce demands.',
  },
  {
    id: 'silverstone',
    name: 'Silverstone Circuit',
    location: 'Northamptonshire',
    country: 'United Kingdom',
    flag: '🇬🇧',
    lengthKm: 5.891,
    laps: 52,
    corners: 18,
    drsZones: 2,
    lapRecord: { time: '1:27.097', driver: 'Max Verstappen', year: 2020 },
    svgPath: 'M 60 140 L 180 60 L 320 60 L 420 120 L 380 240 L 280 280 L 180 220 L 120 280 L 60 200 Z',
    sectors: [
      { id: 1, name: 'S1: Abbey, Farm & Village', lengthKm: 1.82 },
      { id: 2, name: 'S2: Maggotts, Becketts & Chapel', lengthKm: 2.15 },
      { id: 3, name: 'S3: Stowe, Vale & Club', lengthKm: 1.921 },
    ],
    description: 'Home of British motorsport featuring legendary high-speed corner sequences like Maggotts, Becketts, and Chapel pushing lateral G-forces to 5.2G.',
  },
  {
    id: 'spa',
    name: 'Circuit de Spa-Francorchamps',
    location: 'Stavelot',
    country: 'Belgium',
    flag: '🇧🇪',
    lengthKm: 7.004,
    laps: 44,
    corners: 19,
    drsZones: 2,
    lapRecord: { time: '1:46.286', driver: 'Valtteri Bottas', year: 2018 },
    svgPath: 'M 80 260 L 120 180 L 180 120 L 260 60 L 380 80 L 440 180 L 360 260 L 280 300 L 160 320 Z',
    sectors: [
      { id: 1, name: 'S1: La Source & Eau Rouge / Raidillon', lengthKm: 2.31 },
      { id: 2, name: 'S2: Les Combes & Pouhon', lengthKm: 2.85 },
      { id: 3, name: 'S3: Stavelot & Blanchimont', lengthKm: 1.844 },
    ],
    description: 'A rollercoaster through the Ardennes forest with massive elevation changes, unpredictable weather micro-climates, and the iconic uphill Eau Rouge compression.',
  },
  {
    id: 'monza',
    name: 'Autodromo Nazionale Monza',
    location: 'Monza',
    country: 'Italy',
    flag: '🇮🇹',
    lengthKm: 5.793,
    laps: 53,
    corners: 11,
    drsZones: 2,
    lapRecord: { time: '1:21.046', driver: 'Rubens Barrichello', year: 2004 },
    svgPath: 'M 60 200 L 380 60 L 420 100 L 400 180 L 340 220 L 220 240 L 100 260 Z',
    sectors: [
      { id: 1, name: 'S1: Prima Variante & Curva Grande', lengthKm: 1.95 },
      { id: 2, name: 'S2: Lesmo 1, Lesmo 2 & Variante del Serraglio', lengthKm: 1.88 },
      { id: 3, name: 'S3: Variante Ascari & Curva Parabolica', lengthKm: 1.963 },
    ],
    description: 'The Temple of Speed. Ultra-low downforce setup where cars exceed 350 km/h down the main straight before heavy braking into tight chicanes.',
  },
  {
    id: 'suzuka',
    name: 'Suzuka International Racing Course',
    location: 'Suzuka',
    country: 'Japan',
    flag: '🇯🇵',
    lengthKm: 5.807,
    laps: 53,
    corners: 18,
    drsZones: 1,
    lapRecord: { time: '1:30.983', driver: 'Lewis Hamilton', year: 2019 },
    svgPath: 'M 100 220 C 140 140, 200 100, 280 120 C 340 140, 400 200, 360 280 C 300 320, 220 280, 180 200 Z',
    sectors: [
      { id: 1, name: 'S1: First Corner & S Curves', lengthKm: 1.89 },
      { id: 2, name: 'S2: Degner & 130R', lengthKm: 2.12 },
      { id: 3, name: 'S3: Casio Triangle & Pit Straight', lengthKm: 1.797 },
    ],
    description: 'Driver favorite figure-of-eight layout featuring rhythm flow S-Curves, Degner corners, and the flat-out 130R sweep into heavy braking.',
  },
  {
    id: 'cota',
    name: 'Circuit of the Americas',
    location: 'Austin, Texas',
    country: 'United States',
    flag: '🇺🇸',
    lengthKm: 5.513,
    laps: 56,
    corners: 20,
    drsZones: 2,
    lapRecord: { time: '1:36.169', driver: 'Charles Leclerc', year: 2019 },
    svgPath: 'M 80 260 L 120 120 L 220 80 L 340 120 L 400 200 L 320 280 L 200 260 Z',
    sectors: [
      { id: 1, name: 'S1: Turn 1 Steep Hill & S-Curves', lengthKm: 1.75 },
      { id: 2, name: 'S2: Back Straight & Hairpin', lengthKm: 2.1 },
      { id: 3, name: 'S3: Stadium Section & Triple Apex T16-18', lengthKm: 1.663 },
    ],
    description: 'Modern classic with a blind uphill Turn 1 crest, high-speed flowing initial sector inspired by Silverstone, and technical arena hairpin turns.',
  },
];

export const DRIVERS: Driver[] = [
  {
    id: 'verstappen',
    number: 1,
    name: 'Max Verstappen',
    shortCode: 'VER',
    team: 'Red Bull Racing',
    teamColor: '#141E46',
    country: 'Netherlands',
    flag: '🇳🇱',
    points: 437,
    position: 1,
    podiums: 111,
    wins: 62,
    poles: 40,
    fastestLaps: 33,
    worldTitles: 4,
    carName: 'RB21',
    biography: 'Relentless speed, uncompromising wheel-to-wheel aggressive racecraft, and extraordinary tyre management under extreme pressure.',
    qualifyingPace: 98,
    raceCraft: 99,
    tireManagement: 97,
    wetWeatherSkill: 99,
  },
  {
    id: 'hamilton',
    number: 44,
    name: 'Lewis Hamilton',
    shortCode: 'HAM',
    team: 'Scuderia Ferrari',
    teamColor: '#E60000',
    country: 'United Kingdom',
    flag: '🇬🇧',
    points: 223,
    position: 2,
    podiums: 201,
    wins: 105,
    poles: 104,
    fastestLaps: 67,
    worldTitles: 7,
    carName: 'SF-25',
    biography: 'Statistically the most successful driver in Formula 1 history. Renowned for supreme wet-weather control, longevity, and late-race surge speed.',
    qualifyingPace: 96,
    raceCraft: 98,
    tireManagement: 98,
    wetWeatherSkill: 99,
  },
  {
    id: 'leclerc',
    number: 16,
    name: 'Charles Leclerc',
    shortCode: 'LEC',
    team: 'Scuderia Ferrari',
    teamColor: '#E60000',
    country: 'Monaco',
    flag: '🇲🇨',
    points: 356,
    position: 3,
    podiums: 42,
    wins: 8,
    poles: 26,
    fastestLaps: 10,
    worldTitles: 0,
    carName: 'SF-25',
    biography: 'Sensational single-lap qualifying specialist and emotional fan favorite, commanding raw instinct around street tracks like Monaco and Baku.',
    qualifyingPace: 99,
    raceCraft: 94,
    tireManagement: 92,
    wetWeatherSkill: 93,
  },
  {
    id: 'norris',
    number: 4,
    name: 'Lando Norris',
    shortCode: 'NOR',
    team: 'McLaren F1 Team',
    teamColor: '#FF8000',
    country: 'United Kingdom',
    flag: '🇬🇧',
    points: 374,
    position: 4,
    podiums: 28,
    wins: 4,
    poles: 8,
    fastestLaps: 12,
    worldTitles: 0,
    carName: 'MCL39',
    biography: 'Spearheading McLaren’s modern resurgence with razor-sharp high-speed cornering confidence and impressive wheel-to-wheel discipline.',
    qualifyingPace: 95,
    raceCraft: 93,
    tireManagement: 94,
    wetWeatherSkill: 94,
  },
  {
    id: 'piastri',
    number: 81,
    name: 'Oscar Piastri',
    shortCode: 'PIA',
    team: 'McLaren F1 Team',
    teamColor: '#FF8000',
    country: 'Australia',
    flag: '🇦🇺',
    points: 292,
    position: 5,
    podiums: 10,
    wins: 2,
    poles: 1,
    fastestLaps: 3,
    worldTitles: 0,
    carName: 'MCL39',
    biography: 'Ice-cool composure, analytical precise racing lines, and astonishing adaptability in high-stress wheel-to-wheel battles.',
    qualifyingPace: 93,
    raceCraft: 95,
    tireManagement: 91,
    wetWeatherSkill: 91,
  },
  {
    id: 'russell',
    number: 63,
    name: 'George Russell',
    shortCode: 'RUS',
    team: 'Mercedes-AMG PETRONAS',
    teamColor: '#00A19C',
    country: 'United Kingdom',
    flag: '🇬🇧',
    points: 245,
    position: 6,
    podiums: 15,
    wins: 3,
    poles: 5,
    fastestLaps: 8,
    worldTitles: 0,
    carName: 'W16',
    biography: 'Extremely detailed engineering focus, formidable qualifying output, and relentless radio strategy communications.',
    qualifyingPace: 95,
    raceCraft: 91,
    tireManagement: 90,
    wetWeatherSkill: 93,
  },
  {
    id: 'alonso',
    number: 14,
    name: 'Fernando Alonso',
    shortCode: 'ALO',
    team: 'Aston Martin Aramco',
    teamColor: '#005A40',
    country: 'Spain',
    flag: '🇪🇸',
    points: 110,
    position: 7,
    podiums: 106,
    wins: 32,
    poles: 22,
    fastestLaps: 26,
    worldTitles: 2,
    carName: 'AMR25',
    biography: 'The master of race intelligence, aggressive start launches, deflecting pressure, and extracting 100% efficiency from any car generation.',
    qualifyingPace: 92,
    raceCraft: 99,
    tireManagement: 97,
    wetWeatherSkill: 97,
  },
];

export const CONSTRUCTORS: Constructor[] = [
  {
    id: 'mclaren',
    name: 'McLaren F1 Team',
    teamPrincipal: 'Andrea Stella',
    powerUnit: 'Mercedes V6 Turbo Hybrid',
    chassis: 'MCL39',
    color: '#FF8000',
    secondaryColor: '#1A1A1A',
    points: 666,
    position: 1,
    wins: 6,
    podiums: 38,
    drivers: ['NOR', 'PIA'],
  },
  {
    id: 'ferrari',
    name: 'Scuderia Ferrari',
    teamPrincipal: 'Frédéric Vasseur',
    powerUnit: 'Ferrari 066/12 V6',
    chassis: 'SF-25',
    color: '#E60000',
    secondaryColor: '#FFEB00',
    points: 652,
    position: 2,
    wins: 5,
    podiums: 26,
    drivers: ['LEC', 'HAM'],
  },
  {
    id: 'redbull',
    name: 'Red Bull Racing',
    teamPrincipal: 'Christian Horner',
    powerUnit: 'Honda RBPT V6',
    chassis: 'RB21',
    color: '#141E46',
    secondaryColor: '#FF1801',
    points: 589,
    position: 3,
    wins: 9,
    podiums: 20,
    drivers: ['VER', 'LAW'],
  },
  {
    id: 'mercedes',
    name: 'Mercedes-AMG PETRONAS',
    teamPrincipal: 'Toto Wolff',
    powerUnit: 'Mercedes V6 Turbo Hybrid',
    chassis: 'W16',
    color: '#00A19C',
    secondaryColor: '#C0C0C0',
    points: 468,
    position: 4,
    wins: 3,
    podiums: 15,
    drivers: ['RUS', 'ANT'],
  },
  {
    id: 'astonmartin',
    name: 'Aston Martin Aramco',
    teamPrincipal: 'Mike Krack',
    powerUnit: 'Mercedes V6 Turbo Hybrid',
    chassis: 'AMR25',
    color: '#005A40',
    secondaryColor: '#CEDC00',
    points: 92,
    position: 5,
    wins: 0,
    podiums: 0,
    drivers: ['ALO', 'STR'],
  },
];

export const RADIO_QUOTES: RadioQuote[] = [
  {
    id: 'kimi-alone',
    driver: 'Kimi Räikkönen',
    team: 'Lotus F1',
    event: 'Abu Dhabi GP',
    year: 2012,
    audioText: 'Just leave me alone, I know what I am doing!',
    context: 'When race engineer Simon Rennie gave tire update warnings while Kimi was leading comfortably.',
    category: 'Iconic',
  },
  {
    id: 'alonso-gp2',
    driver: 'Fernando Alonso',
    team: 'McLaren Honda',
    event: 'Japanese GP (Suzuka)',
    year: 2015,
    audioText: 'GP2 Engine! GP2! ARGH!',
    context: 'Frustrated on the main straight as Sauber passed the McLaren on home Honda soil.',
    category: 'Radio Meltdown',
  },
  {
    id: 'toto-mikey',
    driver: 'Toto Wolff',
    team: 'Mercedes AMG',
    event: 'Abu Dhabi GP',
    year: 2021,
    audioText: 'No Mikey, no no Mikey! That was so not right!',
    context: 'Direct call to Race Director Michael Masi during the infamous late safety car restart.',
    category: 'Iconic',
  },
  {
    id: 'vettel-mein-gott',
    driver: 'Sebastian Vettel',
    team: 'Ferrari',
    event: 'German GP',
    year: 2018,
    audioText: 'Mein Gott muss das sein?! So ein Bockmist aber auch!',
    context: 'Impacting the barrier in wet conditions at Sachs Curve while leading his home race.',
    category: 'Radio Meltdown',
  },
  {
    id: 'sainz-smooth',
    driver: 'Carlos Sainz',
    team: 'McLaren / Ferrari',
    event: 'Multiple Races',
    year: 2019,
    audioText: 'Smooooth Operaaator... Smooooth Operaaator!',
    context: 'Singing after securing podium finishes and dominant overtakes.',
    category: 'Funny',
  },
  {
    id: 'leclerc-no',
    driver: 'Charles Leclerc',
    team: 'Ferrari',
    event: 'French GP (Paul Ricard)',
    year: 2022,
    audioText: 'NOOOOOOOOOOO!',
    context: 'Anguished scream echoing through pit radio after spinning out from P1.',
    category: 'Radio Meltdown',
  },
  {
    id: 'verstappen-multi',
    driver: 'Max Verstappen',
    team: 'Red Bull Racing',
    event: 'Brazilian GP',
    year: 2022,
    audioText: 'I told you already last time, guys, don’t ask me that again! I gave my reasons!',
    context: 'Refusing team orders to swap position with teammate Perez on the final lap.',
    category: 'Tactical',
  },
];

export const AERO_HOTSPOTS: AeroHotspot[] = [
  {
    id: 'venturi-floor',
    title: 'Venturi Ground Effect Tunnels',
    category: 'Aerodynamics',
    shortDesc: 'Generates up to 60% of total car downforce via suction under floor.',
    detailedExplanation: 'Underbody venturi tunnels channel high-velocity air under the chassis, creating a localized low-pressure zone (Bernoulli Principle) that sucks the car down onto the tarmac with minimal aerodynamic drag compared to top-side wings.',
    specs: [
      { label: 'Downforce Contribution', value: '~60%' },
      { label: 'Tunnel Ride Height Target', value: '15mm - 25mm' },
      { label: 'Suction Force at 300km/h', value: '1,800 kg' },
    ],
    coordinates: { x: 50, y: 72 },
  },
  {
    id: 'drs-rear-wing',
    title: 'DRS & Active Rear Wing Assembly',
    category: 'Aerodynamics',
    shortDesc: 'Hydraulic flap opening reduces drag by 20% on overtaking straights.',
    detailedExplanation: 'Drag Reduction System (DRS) opens a 85mm gap in the top rear wing element when within 1.0 second of a car ahead at designated detection points, granting an instant +10 to +18 km/h speed advantage down straights.',
    specs: [
      { label: 'Maximum Flap Opening', value: '85 mm' },
      { label: 'Top Speed Gain', value: '+12 to +18 km/h' },
      { label: 'Actuation Method', value: 'Hydraulic Actuator (<0.1s)' },
    ],
    coordinates: { x: 88, y: 35 },
  },
  {
    id: 'power-unit-mgu-k',
    title: '1.6L V6 Turbo Hybrid + MGU-K / MGU-H',
    category: 'Power Unit',
    shortDesc: 'Produces over 1,000+ horsepower at 15,000 RPM with 50%+ thermal efficiency.',
    detailedExplanation: 'Combines a direct-injection 1.6-liter V6 turbocharged internal combustion engine (ICE) with two electric motor generator units: MGU-K (harvests brake kinetic energy, outputs 120kW/160hp) and MGU-H (harvests exhaust heat energy).',
    specs: [
      { label: 'Peak Power Output', value: '1,020+ HP' },
      { label: 'Max Engine Rev Limit', value: '15,000 RPM' },
      { label: 'Thermal Efficiency', value: '>52%' },
    ],
    coordinates: { x: 55, y: 42 },
  },
  {
    id: 'halo-titanium',
    title: 'Grade 5 Titanium Halo Safety Ring',
    category: 'Safety',
    shortDesc: 'Surrounds cockpit, withstands 125 kN of impact force (weight of 2 double-decker buses).',
    detailedExplanation: 'Introduced in 2018, the 9kg titanium structure is mounted directly onto the carbon fiber monocoque survival cell. Has saved multiple driver lives in high-speed crashes (e.g. Grosjean Bahrain 2020, Zhou Silverstone 2022).',
    specs: [
      { label: 'Material', value: 'Grade 5 Titanium' },
      { label: 'Load Capacity', value: '125 kN (12.5 Tons)' },
      { label: 'Structure Weight', value: '9.0 kg' },
    ],
    coordinates: { x: 42, y: 30 },
  },
  {
    id: 'carbon-brakes',
    title: 'Carbon-Carbon 1000°C Disc Brakes',
    category: 'Suspension & Brakes',
    shortDesc: 'Stops 798kg car from 330 km/h to 100 km/h in just 1.8 seconds at 5G deceleration.',
    detailedExplanation: 'Carbon fiber matrix brake discs with over 1,400 cooling ventilation holes operating at optimal temperatures between 400°C and 1,000°C. Drivers exert up to 160kg of leg pressure on the brake pedal into heavy stops.',
    specs: [
      { label: 'Max Operating Temp', value: '1,050°C' },
      { label: 'Peak Deceleration', value: '5.5 G' },
      { label: 'Cooling Holes', value: '~1,400 per disc' },
    ],
    coordinates: { x: 28, y: 60 },
  },
];

export const DEFAULT_TRIVIA: TriviaQuestion[] = [
  {
    id: 'q1',
    question: 'Who holds the record for the fastest pit stop in Formula 1 history?',
    options: ['Red Bull Racing (1.82s)', 'McLaren F1 Team (1.80s)', 'Ferrari (1.90s)', 'Mercedes AMG (1.88s)'],
    correctIndex: 1,
    explanation: 'McLaren set the official world record with a 1.80-second tire change on Lando Norris’ car at the 2023 Qatar Grand Prix!',
    funFact: 'All 4 tires were removed and replaced in less time than it takes a human to blink twice.',
  },
  {
    id: 'q2',
    question: 'What is the minimum weight of an F1 car (including driver) under current regulations?',
    options: ['750 kg', '798 kg', '820 kg', '730 kg'],
    correctIndex: 1,
    explanation: 'The FIA minimum weight limit is set at 798 kg (without fuel). Ballast is placed in the floor to reach this exact limit.',
  },
  {
    id: 'q3',
    question: 'What happens when a red flag is displayed during an F1 race?',
    options: [
      'Cars drive at full speed back to the garage',
      'The race is cancelled immediately without points',
      'Session is suspended, all cars reduce speed and enter pit lane',
      'Safety car stays out indefinitely while racing continues',
    ],
    correctIndex: 2,
    explanation: 'A red flag immediately halts the session for severe weather or dangerous track debris. Drivers slow down and line up in pit lane fast-lane.',
  },
  {
    id: 'q4',
    question: 'What does DRS stand for in Formula 1?',
    options: [
      'Direct Radial Steering',
      'Drag Reduction System',
      'Driver Response Sensor',
      'Dynamic Stability System',
    ],
    correctIndex: 1,
    explanation: 'DRS (Drag Reduction System) opens a flap on the rear wing on designated straights to shed drag and promote overtaking.',
  },
];
